# Generated by Django 5.0.2 on 2025-01-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_goal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.AlterField(
            model_name='professor',
            name='second_lastname',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='second_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
